name: Publish Stremio Addon
description: Submit a new Stremio Addon to the Unofficial Stremio Addons List
title: "Addon Name"
labels: ["pending approval"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a new Stremio addon!
  - type: input
    id: addon-url
    attributes:
      label: Addon Manifest URL
      description: What is the addon manifest URL? (ends with "/manifest.json")
      placeholder: ex. https://addon.server.com/manifest.json
    validations:
      required: true
  - type: textarea
    id: addon-description
    attributes:
      label: Addon Description
      description: Describe the addon you are submitting.
      placeholder: My amazing new addon!
    validations:
      required: false
  - type: dropdown
    id: lang
    attributes:
      label: Language of Content
      description: Choose the language in which the streams / metadata show. (if applicable)
      options:
        - Multilingual (Default)
        - Abkhazian (ab-AB)
        - Afar (aa-AA)
        - Afrikaans (af-ZA)
        - Akan (ak-AK)
        - Albanian (sq-AL)
        - Amharic (am-AM)
        - Arabic (ar-SA)
        - Arabic (ar-AE)
        - Arabic (ar-DZ)
        - Aragonese (an-AN)
        - Armenian (hy-HY)
        - Assamese (as-AS)
        - Avaric (av-AV)
        - Avestan (ae-AE)
        - Aymara (ay-AY)
        - Azerbaijani (az-AZ)
        - Bambara (bm-BM)
        - Bashkir (ba-BA)
        - Basque (eu-ES)
        - Belarusian (be-BY)
        - Bengali (bn-BD)
        - Bislama (bi-BI)
        - Bosnian (bs-BS)
        - Breton (br-BR)
        - Bulgarian (bg-BG)
        - Burmese (my-MY)
        - Cantonese (cn-CN)
        - Catalan; Valencian (ca-ES)
        - Central Khmer (km-KM)
        - Chamorro (ch-GU)
        - Chechen (ce-CE)
        - Chichewa; Chewa; Nyanja (ny-NY)
        - Chinese (zh-CN)
        - Chinese (zh-HK)
        - Chinese (zh-SG)
        - Chinese (zh-TW)
        - Chuvash (cv-CV)
        - Cornish (kw-KW)
        - Corsican (co-CO)
        - Cree (cr-CR)
        - Croatian (hr-HR)
        - Czech (cs-CZ)
        - Danish (da-DK)
        - Divehi; Dhivehi; Maldivian (dv-DV)
        - Dutch; Flemish (nl-NL)
        - Dutch; Flemish (nl-BE)
        - Dzongkha (dz-DZ)
        - English (en-US)
        - English (en-AU)
        - English (en-CA)
        - English (en-GB)
        - English (en-IE)
        - English (en-NZ)
        - Esperanto (eo-EO)
        - Estonian (et-EE)
        - Ewe (ee-EE)
        - Faroese (fo-FO)
        - Fijian (fj-FJ)
        - Finnish (fi-FI)
        - French (fr-FR)
        - French (fr-CA)
        - Fulah (ff-FF)
        - Gaelic; Scottish Gaelic (gd-GB)
        - Galician (gl-ES)
        - Ganda (lg-LG)
        - Georgian (ka-GE)
        - German (de-DE)
        - German (de-AT)
        - German (de-CH)
        - Greek (el-GR)
        - Guarani (gn-GN)
        - Gujarati (gu-GU)
        - Haitian; Haitian Creole (ht-HT)
        - Hausa (ha-HA)
        - Hebrew (he-IL)
        - Herero (hz-HZ)
        - Hindi (hi-IN)
        - Hiri Motu (ho-HO)
        - Hungarian (hu-HU)
        - Icelandic (is-IS)
        - Ido (io-IO)
        - Igbo (ig-IG)
        - Indian (General)
        - Indonesian (id-ID)
        - Inuktitut (iu-IU)
        - Inupiaq (ik-IK)
        - Irish (ga-IE)
        - Italian (it-IT)
        - Japanese (ja-JP)
        - Javanese (jv-JV)
        - Kannada (kn-IN)
        - Kanuri (kr-KR)
        - Kashmiri (ks-KS)
        - Kazakh (kk-KZ)
        - Kikuyu; Gikuyu (ki-KI)
        - Kinyarwanda (rw-RW)
        - Kirghiz; Kyrgyz (ky-KG)
        - Komi (kv-KV)
        - Kongo (kg-KG)
        - Korean (ko-KR)
        - Kurdish (ku-KU)
        - Lao (lo-LO)
        - Latin (la-LA)
        - Latvian (lv-LV)
        - Lingala (ln-LN)
        - Lithuanian (lt-LT)
        - Luba-Katanga (lu-LU)
        - Luxembourgish; Letzeburgesch (lb-LB)
        - Macedonian (mk-MK)
        - Malagasy (mg-MG)
        - Malay (ms-MY)
        - Malay (ms-SG)
        - Malayalam (ml-IN)
        - Maltese (mt-MT)
        - Manx (gv-GV)
        - Maori (mi-MI)
        - Marathi (mr-IN)
        - Marshallese (mh-MH)
        - Moldavian; Moldovan (mo-MO)
        - Mongolian (mn-MN)
        - Nauru (na-NA)
        - Navajo; Navaho (nv-NV)
        - Ndonga (ng-NG)
        - Nepali (ne-NE)
        - Northern Sami (se-SE)
        - Norwegian (no-NO)
        - Occitan (post 1500) (oc-OC)
        - Ojibwa (oj-OJ)
        - Oriya (or-OR)
        - Oromo (om-OM)
        - Pali (pi-PI)
        - Panjabi; Punjabi (pa-IN)
        - Persian (fa-IR)
        - Polish (pl-PL)
        - Portuguese (pt-PT)
        - Brazilian Portuguese (pt-BR)
        - Pushto; Pashto (ps-PS)
        - Quechua (qu-QU)
        - Romanian (ro-RO)
        - Romansh (rm-RM)
        - Rundi (rn-RN)
        - Russian (ru-RU)
        - Samoan (sm-SM)
        - Sango (sg-SG)
        - Sanskrit (sa-SA)
        - Sardinian (sc-SC)
        - Serbian (sr-RS)
        - Serbo-Croatian (sh-SH)
        - Shona (sn-SN)
        - Sichuan Yi; Nuosu (ii-II)
        - Sindhi (sd-SD)
        - Sinhala; Sinhalese (si-LK)
        - Slovak (sk-SK)
        - Slovenian (sl-SI)
        - Somali (so-SO)
        - Sotho, Southern (st-ST)
        - Spanish; Castilian (es-ES)
        - Spanish; Castilian (es-MX)
        - Sundanese (su-SU)
        - Swahili (sw-SW)
        - Swati (ss-SS)
        - Swedish (sv-SE)
        - Tagalog (tl-PH)
        - Tahitian (ty-TY)
        - Tajik (tg-TG)
        - Tamil (ta-IN)
        - Tatar (tt-TT)
        - Telugu (te-IN)
        - Thai (th-TH)
        - Tibetan (bo-BO)
        - Tigrinya (ti-TI)
        - Tonga (Tonga Islands) (to-TO)
        - Tsonga (ts-TS)
        - Tswana (tn-TN)
        - Turkish (tr-TR)
        - Turkmen (tk-TK)
        - Twi (tw-TW)
        - Uighur; Uyghur (ug-UG)
        - Ukrainian (uk-UA)
        - Urdu (ur-UR)
        - Uzbek (uz-UZ)
        - Venda (ve-VE)
        - Vietnamese (vi-VN)
        - Volapük (vo-VO)
        - Walloon (wa-WA)
        - Welsh (cy-GB)
        - Western Frisian (fy-FY)
        - Wolof (wo-WO)
        - Xhosa (xh-XH)
        - Yiddish (yi-YI)
        - Yoruba (yo-YO)
        - Zhuang; Chuang (za-ZA)
        - Zulu (zu-ZA)
  - type: checkboxes
    id: labels
    attributes:
      label: Choose Labels
      description: Choose the labels that best describe your addon.
      options:
        - label: anime
        - label: asian drama
        - label: bollywood
        - label: cartoons
        - label: debrid support
        - label: http streams
        - label: live tv
        - label: metadata
        - label: misc
        - label: movies
        - label: music
        - label: nsfw
        - label: podcasts
        - label: radios
        - label: subtitles
        - label: torrents
        - label: tv shows
        - label: video games
