# .github/workflows/main.yml

name: Trigger Netlify Build Daily
on:
  schedule:
    # Run at minute 25 every 2 hours
    - cron: '25 */2 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_WEBHOOK }}
